server:
  port: 20001
  base:
    url: http://192.168.4.64:20001

spring:
  thymeleaf:
    cache: false

keycloak:
  token:
    url: http://192.168.4.86:8080/auth/realms/TestPKCE/protocol/openid-connect/token
  auth:
    url: http://192.168.4.86:8080/auth/realms/TestPKCE/protocol/openid-connect/auth
  client:
    create:
      url: http://192.168.4.86:8080/auth/realms/TestPKCE/clients-registrations/default
    id: onyx-integrator-client
    redirect:
      url: http://192.168.4.64:20001/callback